In [15]:
#task1:
# use unique to find the unique items of these two arrays

import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6]) 
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8]) 
a_unique = np.unique(a)
b_unique = np.unique(b)
print('a_unique:',a_unique)
print('b_unique:',b_unique)

a_unique: [1 2 3 4 5 6]
b_unique: [ 2  4  7  8  9 10]


In [16]:
#use intersect to extract the common items between these two arrays

print(np.intersect1d(a_unique, b_unique))

[2 4]


In [19]:
#task2:
#Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. 

arr = np.arange(1,16).reshape(3,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [20]:
#Arrays have the transpose method and also the special T attribute.

arr.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [24]:
#task3:
#use in1d function to extract the items between these two arrays and also can remove the common items

a = np.array([12, 5, 7, 15, 3, 1, 8]) 
b = np.array([14, 6, 3, 11, 19, 12, 5]) 

mask = np.in1d(a,b,invert=True)
print(mask)
print(a[mask])

[False False  True  True False  True  True]
[ 7 15  1  8]


In [25]:
#task4:
#At first i searched from internet the entire distance between NYC and Key West is 1436 miles.
#use random.randint method to generate 35 random numbers between 0 and 1436,and the largest number is 1436
#use for loop to select 4 inconsecutive numbers which is equal to the last number.
#use sort function to keep the number increase 

import numpy as np
record_mile = np.random.randint(1,1436,35)

for x in np.random.randint(1,34,4):
    record_mile[x] = record_mile[x-1]
    
record_mile[34] = 1436
day_mile = np.sort(record_mile)
print(day_mile)

i = day_mile[0]
each_day = np.append(i,np.diff(day_mile))
print(each_day)

[   4   12   42  101  134  175  181  220  326  326  365  369  423  471
  505  516  690  786  799  804  822  830  835  835  945 1033 1057 1223
 1252 1252 1326 1371 1373 1424 1436]
[  4   8  30  59  33  41   6  39 106   0  39   4  54  48  34  11 174  96
  13   5  18   8   5   0 110  88  24 166  29   0  74  45   2  51  12]


In [4]:
#Task 5:
import pandas
import numpy as np

# supress scientific notation
np.set_printoptions(suppress = True)

# read the data file from GitHub and convert to a NumPy ndarray object
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()

# verify you have an ndarray object
type(nyc_water)


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  if __name__ == '__main__':


numpy.ndarray

In [5]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [6]:
#Question1:

np.amax(nyc_water[:,2])

1512.0

In [7]:
#Question2:

nyc_water.shape[0]

39

In [8]:
#Question3:

print(np.mean(nyc_water[:,3]))

print(np.std(nyc_water[:,3]))

160.30769230769232
31.51894330370624


In [9]:
#Question4:

pop_diff = np.diff(nyc_water[:,1])

print(pop_diff)

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
